openapi: 3.0.0
info:
  title: 企業求人情報API
  version: 1.0.0
  description: 企業情報と求人情報の管理を行うAPI

servers:
  - url: /api/v1

components:
  schemas:
    Company:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        business_description:
          type: string
          nullable: true
        custom_fields:
          type: array
          items:
            $ref: '#/components/schemas/CustomField'
        job_postings:
          type: array
          items:
            $ref: '#/components/schemas/JobPosting'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - id
        - name
        - created_at
        - updated_at

    CustomField:
      type: object
      properties:
        id:
          type: integer
          format: int64
        field_name:
          type: string
        content:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - id
        - field_name
        - content
        - created_at
        - updated_at

    JobPosting:
      type: object
      properties:
        id:
          type: integer
          format: int64
        company_id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
          nullable: true
        custom_fields:
          type: array
          items:
            $ref: '#/components/schemas/JobCustomField'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - id
        - company_id
        - title
        - created_at
        - updated_at

    JobCustomField:
      type: object
      properties:
        id:
          type: integer
          format: int64
        field_name:
          type: string
        content:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - id
        - field_name
        - content
        - created_at
        - updated_at

    CompanyInput:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
        business_description:
          type: string
          maxLength: 1000
          nullable: true
        custom_fields:
          type: array
          items:
            $ref: '#/components/schemas/CustomFieldInput'
      required:
        - name

    CustomFieldInput:
      type: object
      properties:
        field_name:
          type: string
          minLength: 1
          maxLength: 50
        content:
          type: string
          maxLength: 500
      required:
        - field_name
        - content

    JobPostingInput:
      type: object
      properties:
        company_id:
          type: integer
          format: int64
        title:
          type: string
          minLength: 1
          maxLength: 100
        description:
          type: string
          maxLength: 1000
          nullable: true
        custom_fields:
          type: array
          items:
            $ref: '#/components/schemas/JobCustomFieldInput'
      required:
        - company_id
        - title

    JobCustomFieldInput:
      type: object
      properties:
        field_name:
          type: string
          minLength: 1
          maxLength: 50
        content:
          type: string
          maxLength: 500
      required:
        - field_name
        - content

paths:
  /companies:
    get:
      summary: 企業求人情報の取得
      description: 全ての企業情報とそれに紐付く求人情報を取得します
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            minimum: 1
          description: ページ番号
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 6
          description: 1ページあたりの件数。デフォルト値は6です。
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  companies:
                    type: array
                    items:
                      $ref: '#/components/schemas/Company'
                  total:
                    type: integer
                  page:
                    type: integer
                  limit:
                    type: integer
                required:
                  - companies
                  - total
                  - page
                  - limit
        '400':
          description: 不正なリクエスト
        '500':
          description: サーバーエラー

    post:
      summary: 企業情報の作成
      description: 新しい企業情報を作成します
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompanyInput'
      responses:
        '201':
          description: 作成成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
        '400':
          description: バリデーションエラー
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        example: "VALIDATION_ERROR"
                      message:
                        type: string
                        example: "バリデーションエラー"
                      details:
                        type: array
                        items:
                          type: object
                          properties:
                            field:
                              type: string
                              example: "name"
                            message:
                              type: string
                              example: "企業名は必須です"
        '500':
          description: サーバーエラー

  /companies/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
        description: 企業ID

    put:
      summary: 企業情報の更新
      description: 指定された企業の情報を更新します
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompanyInput'
      responses:
        '200':
          description: 更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
        '400':
          description: 不正なリクエスト
        '404':
          description: 企業が見つかりません
        '500':
          description: サーバーエラー

    delete:
      summary: 企業情報の削除
      description: 指定された企業の情報を削除します
      responses:
        '204':
          description: 削除成功
        '404':
          description: 企業が見つかりません
        '500':
          description: サーバーエラー

  /job-postings:
    post:
      summary: 求人情報の作成
      description: 新しい求人情報を作成します
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JobPostingInput'
      responses:
        '201':
          description: 作成成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobPosting'
        '400':
          description: 不正なリクエスト
        '500':
          description: サーバーエラー

  /job-postings/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
        description: 求人ID

    put:
      summary: 求人情報の更新
      description: 指定された求人情報を更新します
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JobPostingInput'
      responses:
        '200':
          description: 更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobPosting'
        '400':
          description: 不正なリクエスト
        '404':
          description: 求人が見つかりません
        '500':
          description: サーバーエラー

    delete:
      summary: 求人情報の削除
      description: 指定された求人情報を削除します
      responses:
        '204':
          description: 削除成功
        '404':
          description: 求人が見つかりません
        '500':
          description: サーバーエラー 